routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\controllers\UploadController;

use App\Mail\SampleMail;

use App\Http\controllers\LoginAuthController;

use App\Http\controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view ('welcome');
});

Auth::routes();

Route::get('user/profile', 'HomeController@edit')->name('user.edit.profile');
Route::put('user/profile', 'HomeController@upload')->name('users.update.Profile');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('admin/home', 'HomeController@handleAdmin')->name('admin.home')->middleware('is_admin');

Route::resource("blog",'AddController');

Route::resource("texts_add", 'TextController');

Route::resource("blog_add", "ScheduleController");

Route::post('/comment/store', 'CommentController@store')->name('comment.add');

Route::get('file','FileControllers@index')->name('multiple.file');
Route::post('save', 'FileControllers@show')->name('multiple.show');

Route::get('/stripe-payment','StripeController@paymentIndex')->name('stripe.payment');
Route::post('stripe-payment','StripeController@paymentStatus')->name('stripe.status');

Route::get('/users', 'CacheController@index')->name('users.index');
Route::post('/users/search','CacheController@search')->name('users.search');



// Route::resource('/store', 'ContactController');

// Route::get('contact', 'BasicController@index');

// // Route::view("upload", 'upload');
// Route::get('upload', 'UploadController@changes');
// Route::post('upload', 'UploadController@changesfile')->name('changes.file');


//Laravel Session Login Deatails.......

// Route::get('login', function(){

// 	if (session()->has('user')) {
		
// 		return redirect('profile');
// 	}

// 	return view ('login');

// });

// Route::post('/user', 'LoginAuthController@sessionLogin');

// Route::view("profile", 'profile');


// Route::get('logout', function(){

// 	if (session()->has('user')) {
		
// 		session()->pull('user');
// 	}

// 	return view ('login');

// });

// Route::get('product','ProductControllers@product')->name('product.name');
// // Route::get('products/{id}', 'ProductControllers@product')->where('id', '[0-9]');

// Route::get('products/{name}/{id}', 'ProductControllers@product')->where([

// 	'name' => '[a-z]',
// 	'id' => '[0-9]'
// ]);


// Route::get('place','HelperController@helper')->name('helper.name');
	

// Route::get('/email','MailController@sendEmail');

// Route::get('excel','EmployeeController@add');
// Route::get('explode-excel','EmployeeController@exportIntoExcel');
// Route::get('explode-csv','EmployeeController@exportIntoCSV');

// Route::get('check{name}','StudentController@create')->name('create.route');

// Route::view("user", 'user')->middleware('product');
// Route::view("first", 'first');
// Route::view("noaccess", 'noaccess');
// //group middleware

// Route::group(['middleware' =>['productpage']],function(){

//     // Route::view("user", 'user');
// });

// Route::resource('users','NewController');

app/Schedule.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class Schedule extends Model
{
    use Notifiable;

   
    protected $fillable = [
        'title', 'body', 'image',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    //  public function comments()
    // {
    //     return $this->hasMany(Comment::class);
    // }

     public function comments()
    {
        return $this->hasMany(Comment::class)->whereNull('parent_id');
    }
}

app/Http/Controllers/ScheduleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Schedule;

class ScheduleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $schedules = Schedule::all();
        return view('schedule.view',compact('schedules'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('schedule.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $schedules = new Schedule();

        $schedules->title = $request->get('title');
        $schedules->body = $request->get('body');
        $file_name = time().'.'.$request->image->extension();
        $request->image->move(public_path('myfiles'),$file_name);
        $schedules->image = $file_name;
        $schedules->save();

       return redirect('blog_add')->with('success', 'added Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $schedule = Schedule::find($id);
        return view('schedule.show',compact('schedule'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $schedule = Schedule::find($id);
        return view('schedule.edit',compact('schedule'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $schedules = Schedule::find($id);
        
        $schedules->title = $request->get('title');
        $schedules->body = $request->get('body');
        $file_name = time().'.'.$request->image->extension();
        $request->image->move(public_path('myfiles'),$file_name);
        $schedules->image = $file_name;
        $schedules->save();
        return redirect('blog_add')->with('success', 'Update Successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $schedule = Schedule::find($id);
        $schedule->delete();
        return redirect('blog_add')->with('success', 'Delete Successfully!');
    }
}

resources/views/schedule/commentdisplay.blade.php
@foreach($comments as $comment)
    <div class="display-comment" @if($comment->parent_id != null) style="margin-left:40px;" @endif>
        <strong>{{ $comment->add->first_name }}</strong>
        <p>{{ $comment->body }}</p>
        <a href="" id="reply"></a>
       
        <form method="post" action="{{ route('comment.add') }}">
            @csrf
            <div class="form-group">
                <input type="text" name="body" class="form-control" />
                <input type="hidden" name="schedule_id" value="{{ $schedule_id }}" />
                <input type="hidden" name="parent_id" value="{{ $comment->id }}" />
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-warning" value="Reply" />
            </div>
          
        </form>
        @include('schedule.commentdisplay', ['comments' => $comment->replies])
    </div>
@endforeach

resources/views/schedule/create.blade.php
@extends('layouts.app')

@extends('layouts.header')

@section('content')


<hr>
<form action="{{route('blog_add.store')}}" method="post" enctype="multipart/form-data">
@csrf
<div class="container">

    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control"  name="title">
    </div>
     <div class="form-group">
        <label for="body">Text</label>
        <textarea type="text" class="form-control" name="body" rows="10px"></textarea>
    </div>
 
    <div class="form-group">
        <label for="image"> Picture</label>
        <input type="file" class="form-control" name="image">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>

    </div>
</form>

   @endsection

resources/views/schedule/edit.blade.php
@extends('layouts.app')



@section('content')


<hr>
<form action="{{route('blog_add.update', $schedule->id)}}" method="post" enctype="multipart/form-data">
@csrf
@method('PATCH')

<div class="container">

    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control"  name="title" value="{{ $schedule->title}}">
    </div>
     <div class="form-group">
        <label for="body">Text</label>
        <textarea type="text" class="form-control" name="body">{{ $schedule->body}}"</textarea>
    </div>
 
    <div class="form-group">
        <label for="image"> Picture</label>
        <input type="file" class="form-control" name="image" value="{{ $schedule->image}}">
    </div>


   
    <button type="submit" class="btn btn-primary">Update</button>
    <button type="submit" class="btn btn-primary">Reset</button>

    </div>
</form>

   @endsection

resources/views/schedule/show.blade.php
@extends('layouts.app')

@extends('layouts.header')


@section('content')
<div class="container">
    <div class="row">
       
        <div class="col-lg-1">
            <a class="btn btn-primary" href="{{ url('blog_add') }}"> Back</a>
        </div>
    </div>

    <table class="table table-bordered">
        <tr>
            <th>Title:</th>
            <td>{{ $schedule->title }}</td>
        </tr>
       
        <tr>
            <th>Text:</th>
            <td>{{ $schedule->body }}</td>

    </table>

 @include('schedule.commentdisplay', ['comments' => $schedule->comments, 'schedule_id' => $schedule->id])
    <div class="card">
        <div class="card-block">
            <form method="POST" action="{{ route('comment.add') }}">
                 @csrf
                <div class="form-group">
                     <textarea name="body" placeholder="your commant here..." class="form-control"></textarea>
                      <input type="hidden" name="schedule_id" value="{{ $schedule->id }}" />

                </div>
                <div class="form-group">
                     <button type="sumbit" class="btn btn-primary">Add Comments</button>
                </div>

               
            </form>
        </div>
    </div>

</div>
@endsection

resources/views/schedule/view.blade.php
@extends('layouts.app')
@extends('layouts.header')
@section('content')
@if(session('success'))
 <div class="alert alert-success" role="alert">
 	{{ session('success')}}
 	
 </div>
 @endif
 <a href="{{ route('blog_add.create')}}" class="btn btn-primary">Create </a>
 <ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link" href="{{'/home'}}">Home</a>
  </li>
</ul>
<div class="container">
 <div class="col-sm-12">
 	<div class="row">
 		<table class="table table-striped">
 			<thead>
 				<th>Id</th>
 				<th>Title</th>
 				<th>Text</th>
 				<th>Picture</th>
 				<th>Pay</th>
 				<th>Show</th>
 				<th>Edit</th>
 				<th>Delete</th>
 			</thead>
 			<tbody>
 				@if($schedules)
 				@foreach($schedules as $schedule)
 				<tr>
 				<td>{{ $schedule->id }}</td>
 				<td>{{ $schedule->title }}</td>
 				<td>{{ $schedule->body }}</td>
 				<td><img src="myfiles/{{ $schedule->image }}" style="border-radius: 50%" width="80px"></td>
 				<td><a class="btn btn-success" href="{{route('stripe.payment')}}">Pay Now  (₹100)</a></td>
 				<td><a class="btn btn-info" href="{{ route('blog_add.show',$schedule->id) }}">Show</a></td>
 				<td><a class="btn btn-primary" href="{{ route('blog_add.edit',$schedule->id) }}">Edit</a></td>
 				<td>
 					<form method="post" action="{{ route('blog_add.destroy',$schedule->id)}}">
 						@csrf
 						@method('DELETE')
 						<button class="btn btn-danger" type="sumbit">Delete</button>
 					</form>
 				</td>
 				
 			</tr>
 				@endforeach
 				@endif
 			</tbody>
 			
 		</table>
 			
 			
 		</div>
 		
 	</div>
 	
 </div>
</div>
 @endsection