routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\controllers\UploadController;

use App\Mail\SampleMail;

use App\Http\controllers\LoginAuthController;

use App\Http\controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view ('welcome');
});

Auth::routes();

Route::get('user/profile', 'HomeController@edit')->name('user.edit.profile');
Route::put('user/profile', 'HomeController@upload')->name('users.update.Profile');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('admin/home', 'HomeController@handleAdmin')->name('admin.home')->middleware('is_admin');

Route::resource("blog",'AddController');

Route::resource("texts_add", 'TextController');

Route::resource("blog_add", "ScheduleController");

Route::post('/comment/store', 'CommentController@store')->name('comment.add');

Route::get('file','FileControllers@index')->name('multiple.file');
Route::post('save', 'FileControllers@show')->name('multiple.show');

Route::get('/stripe-payment','StripeController@paymentIndex')->name('stripe.payment');
Route::post('stripe-payment','StripeController@paymentStatus')->name('stripe.status');

Route::get('/users', 'CacheController@index')->name('users.index');
Route::post('/users/search','CacheController@search')->name('users.search');



// Route::resource('/store', 'ContactController');

// Route::get('contact', 'BasicController@index');

// // Route::view("upload", 'upload');
// Route::get('upload', 'UploadController@changes');
// Route::post('upload', 'UploadController@changesfile')->name('changes.file');


//Laravel Session Login Deatails.......

// Route::get('login', function(){

// 	if (session()->has('user')) {
		
// 		return redirect('profile');
// 	}

// 	return view ('login');

// });

// Route::post('/user', 'LoginAuthController@sessionLogin');

// Route::view("profile", 'profile');


// Route::get('logout', function(){

// 	if (session()->has('user')) {
		
// 		session()->pull('user');
// 	}

// 	return view ('login');

// });

// Route::get('product','ProductControllers@product')->name('product.name');
// // Route::get('products/{id}', 'ProductControllers@product')->where('id', '[0-9]');

// Route::get('products/{name}/{id}', 'ProductControllers@product')->where([

// 	'name' => '[a-z]',
// 	'id' => '[0-9]'
// ]);


// Route::get('place','HelperController@helper')->name('helper.name');
	

// Route::get('/email','MailController@sendEmail');

// Route::get('excel','EmployeeController@add');
// Route::get('explode-excel','EmployeeController@exportIntoExcel');
// Route::get('explode-csv','EmployeeController@exportIntoCSV');

// Route::get('check{name}','StudentController@create')->name('create.route');

// Route::view("user", 'user')->middleware('product');
// Route::view("first", 'first');
// Route::view("noaccess", 'noaccess');
// //group middleware

// Route::group(['middleware' =>['productpage']],function(){

//     // Route::view("user", 'user');
// });

// Route::resource('users','NewController');

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Blog extends Model
{
    use Notifiable;

   
    protected $fillable = [
        'name', 'email', 'is_admin', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
      
}

resources/views/blog/create.blade.php
@extends('layouts.app')

@extends('layouts.header')

@section('content')


<hr>
<form action="{{route('texts_add.store')}}" method="post" enctype="multipart/form-data">
@csrf
<div class="container">

    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control"  name="title">
    </div>
     <div class="form-group">
        <label for="body">Text</label>
        <textarea type="text" class="form-control" name="body" rows="10px"></textarea>
    </div>
 
    <div class="form-group">
        <label for="image"> Picture</label>
        <input type="file" class="form-control" name="image">
    </div>

    <div class="form-group">
        <label for="birthdaytime"> Scedule_time</label>
        <input type="datetime-local" id="birthdaytime" class="form-control" name="posted_at">
    </div>


   
    <button type="submit" class="btn btn-primary">Submit</button>

    </div>
</form>

   @endsection

resources/views/blog/edit.blade.php
@extends('layouts.app')



@section('content')


<hr>
<form action="{{route('texts_add.update', $text->id)}}" method="post" enctype="multipart/form-data">
@csrf
@method('PATCH')

<div class="container">

    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control"  name="title" value="{{ $text->title}}">
    </div>
     <div class="form-group">
        <label for="body">Text</label>
        <textarea type="text" class="form-control" name="body">{{ $text->body}}"</textarea>
    </div>
 
    <div class="form-group">
        <label for="image"> Picture</label>
        <input type="file" class="form-control" name="image">
    </div>


   
    <button type="submit" class="btn btn-primary">Update</button>
    <button type="submit" class="btn btn-primary">Reset</button>

    </div>
</form>

   @endsection

resources/views/blog/header.blade.php
<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" href="{{'admin/home'}}">Home</a>
  </li>

  <div class="dropdown">
 <button class="btn btn-outline-primary  dropdown-toggle float-right bulk-action-dropdown text-uppercase" href="#" id="dropdownMenuOutlineButton2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Users Management 
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{{('/blog/create')}}">Add User</a>
    <a class="dropdown-item" href="{{'/blog'}}">View User</a>
  </div>
</div>

  <div class="dropdown">
  <button class="btn btn-outline-primary  dropdown-toggle float-right bulk-action-dropdown text-uppercase" href="#" id="dropdownMenuOutlineButton2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   Blog Management 
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{{'/blog_add/create'}}">Add Blog</a>
    <a class="dropdown-item" href="{{'/blog_add'}}">View Blog</a>
  </div>
</div>
  
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Disabled</a>
  </li>
</ul>

resources/views/blog/show.blade.php
@extends('layouts.app')


@section('content')

    <div class="row">
       
        <div class="col-lg-1">
            <a class="btn btn-primary" href="{{ url('texts_add') }}"> Back</a>
        </div>
    </div>
<div class="container">
    <table class="table table-bordered">
        <tr>
            <th>Title:</th>
            <td>{{ $text->title }}</td>
        </tr>
       
        <tr>
            <th>Text:</th>
            <td>{{ $text->body }}</td>
        </tr>
            <th> Picture:</th>
            <td><img src="myfiles/{{ $text->image }}" style="border-radius: 50%" width="80px"></td>       
        </tr>

    </table>
</div>
@endsection

resources/views/blog/view.blade.php
@extends('layouts.app')

@section('content')
@if(session('success'))
 <div class="alert alert-success" role="alert">
 	{{ session('success')}}
 	
 </div>
 @endif
 <a href="{{ route('texts_add.create')}}" class="btn btn-primary">Create </a>
 <ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link" href="{{'/home'}}">Home</a>
  </li>
</ul>
<div class="container">
 <div class="col-sm-12">
 	<div class="row">
 		<table class="table table-striped">
 			<thead>
 				<th>Id</th>
 				<th>Title</th>
 				<th>Text</th>
 				<th>Picture</th>
 				<th>Show</th>
 				<th>Edit</th>
 				<th>Delete</th>
 			</thead>
 			<tbody>
 				@if($texts)
 				@foreach($texts as $text)
 				<tr>
 				<td>{{ $text->id }}</td>
 				<td>{{ $text->title }}</td>
 				<td>{{ $text->body }}</td>
 				<td><img src="myfiles/{{ $text->image }}" style="border-radius: 50%" width="80px"></td>
 				<td> <a class="btn btn-info" href="{{ route('texts_add.show',$text->id) }}">Show</a></td>
 				<td> <a class="btn btn-primary" href="{{ route('texts_add.edit',$text->id) }}">Edit</a></td>
 				<td>
 					<form method="post" action="{{ route('texts_add.destroy',$text->id)}}">
 						@csrf
 						@method('DELETE')
 						<button class="btn btn-danger" type="sumbit">Delete</button>
 					</form>
 				</td>
 				
 			</tr>
 				@endforeach
 				@endif
 			</tbody>
 			
 		</table>
 			
 			
 		</div>
 		
 	</div>
 	
 </div>
</div>
 @endsection