routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\controllers\UploadController;

use App\Mail\SampleMail;

use App\Http\controllers\LoginAuthController;

use App\Http\controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view ('welcome');
});

Auth::routes();

Route::get('user/profile', 'HomeController@edit')->name('user.edit.profile');
Route::put('user/profile', 'HomeController@upload')->name('users.update.Profile');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('admin/home', 'HomeController@handleAdmin')->name('admin.home')->middleware('is_admin');

Route::resource("blog",'AddController');

Route::resource("texts_add", 'TextController');

Route::resource("blog_add", "ScheduleController");

Route::post('/comment/store', 'CommentController@store')->name('comment.add');

Route::get('file','FileControllers@index')->name('multiple.file');
Route::post('save', 'FileControllers@show')->name('multiple.show');

Route::get('/stripe-payment','StripeController@paymentIndex')->name('stripe.payment');
Route::post('stripe-payment','StripeController@paymentStatus')->name('stripe.status');

Route::get('/users', 'CacheController@index')->name('users.index');
Route::post('/users/search','CacheController@search')->name('users.search');



// Route::resource('/store', 'ContactController');

// Route::get('contact', 'BasicController@index');

// // Route::view("upload", 'upload');
// Route::get('upload', 'UploadController@changes');
// Route::post('upload', 'UploadController@changesfile')->name('changes.file');


//Laravel Session Login Deatails.......

// Route::get('login', function(){

// 	if (session()->has('user')) {
		
// 		return redirect('profile');
// 	}

// 	return view ('login');

// });

// Route::post('/user', 'LoginAuthController@sessionLogin');

// Route::view("profile", 'profile');


// Route::get('logout', function(){

// 	if (session()->has('user')) {
		
// 		session()->pull('user');
// 	}

// 	return view ('login');

// });

// Route::get('product','ProductControllers@product')->name('product.name');
// // Route::get('products/{id}', 'ProductControllers@product')->where('id', '[0-9]');

// Route::get('products/{name}/{id}', 'ProductControllers@product')->where([

// 	'name' => '[a-z]',
// 	'id' => '[0-9]'
// ]);


// Route::get('place','HelperController@helper')->name('helper.name');
	

// Route::get('/email','MailController@sendEmail');

// Route::get('excel','EmployeeController@add');
// Route::get('explode-excel','EmployeeController@exportIntoExcel');
// Route::get('explode-csv','EmployeeController@exportIntoCSV');

// Route::get('check{name}','StudentController@create')->name('create.route');

// Route::view("user", 'user')->middleware('product');
// Route::view("first", 'first');
// Route::view("noaccess", 'noaccess');
// //group middleware

// Route::group(['middleware' =>['productpage']],function(){

//     // Route::view("user", 'user');
// });

// Route::resource('users','NewController');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>


    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
             

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                   
                                 {{ Auth::user()->name }}

                                 @if(Auth::user()->profile_image)
                                   <img class="image rounded-circle"   src="{{asset('/storage/uploads/'.Auth::user()->profile_image)}}" alt="profile_image" style="width: 70px;">
                                @endif

                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('user.edit.profile') }}">
                                      My Profile  
                                    </a>
                                    <a class="dropdown-item" href="{{ route('multiple.file') }}">
                                      Multiple File Uploads  
                                    </a>


                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/create.blade.php
@extends('layouts.app')
@extends('layouts.header')

@section('content')


<hr>
<form action="{{route('blog.store')}}" method="post" enctype="multipart/form-data">
@csrf
<div class="container">

    <div class="form-group">
        <label for="title">First_Name</label>
        <input type="text" class="form-control"  name="first_name">
    </div>
     <div class="form-group">
        <label for="title">Last_Name</label>
        <input type="text" class="form-control"  name="last_name">
    </div>
    <div class="form-group">
        <label for="email">Email</label>
         <input type="email" class="form-control" name="email">
     </div> 
     <div class="form-group">
        <label for="job_title">Job_title</label>
        <input type="text" class="form-control" name="job_title">
    </div>
    <div class="form-group">
        <label for="phone">Phone</label>
        <input type="text" class="form-control" name="phone">
    </div>

    <div class="form-group">
        <label for="place">Place</label>
        <input type="text" class="form-control" name="place">
    </div>

    <div class="form-group">
        <label for="image">Profile Picture</label>
        <input type="file" class="form-control" name="image">
    </div>


   
    <button type="submit" class="btn btn-primary">Submit</button>

    </div>
</form>

   @endsection

resources/views/layouts/edit.blade.php
@extends('layouts.app')
@extends('layouts.header')

@section('content')

<hr>
<form action="{{ route('blog.update',$add->id)}}" method="post" enctype="multipart/form-data">
@csrf
@method('PATCH')

<div class="container">

    <div class="form-group">
        <label for="title">First_Name</label>
        <input type="text" class="form-control"  name="first_name" value="{{$add->first_name}}">
    </div>
     <div class="form-group">
        <label for="title">Last_Name</label>
        <input type="text" class="form-control"  name="last_name" value="{{$add->last_name}}">
    </div>
    <div class="form-group">
        <label for="email">Email</label>
         <input type="email" class="form-control" name="email" value="{{$add->email}}">
     </div> 
     <div class="form-group">
        <label for="job_title">Job_title</label>
        <input type="text" class="form-control" name="job_title" value="{{$add->job_title}}">
    </div>
    <div class="form-group">
        <label for="phone">Phone</label>
        <input type="text" class="form-control" name="phone" value="{{$add->phone}}">
    </div>

    <div class="form-group">
        <label for="place">Place</label>
        <input type="text" class="form-control" name="place" value="{{$add->place}}">
    </div>

    <div class="form-group">
        <label for="image">Profile Picture</label>
        <input type="file" class="form-control" name="image" value="{{$add->image}}">
    </div>

   
    <button type="submit" class="btn btn-primary">Update</button>
    <button type="submit" class="btn btn-light">Reset</button>
</div>
</form>

   @endsection

resources/views/layouts/header.blade.php
<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" href="{{'/home'}}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{('/texts_add/create')}}">Schedule Add</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{('/texts_add')}}">View Schedule</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{('/blog_add/create')}}">Blog</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{('/blog_add')}}">View Blogs</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{('blog/create')}}">Add User</a>
  </li>
   <li class="nav-item">
    <a class="nav-link" href="{{('/blog')}}">View Users</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{('/admin/home' )}}">Back Admin</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Disabled</a>
  </li>
</ul>

resources/views/layouts/show.blade.php
@extends('layouts.app')
@extends('layouts.header')
@section('content')
@if(session('success'))
 <div class="alert alert-success" role="alert">
 	{{ session('success')}}
 	
 </div>
 @endif
 <a href="{{ route('blog.create')}}" class="btn btn-primary">Create </a>
<div class="container">
 <div class="col-sm-12">
 	<div class="row">
 		<table class="table table-striped">
 			<thead>
 				<th>Id</th>
 				<th>First_Name</th>
 				<th>Last_Name</th>
 				<th>Email</th>
 				<th>Job_title</th>
 				<th>Phone</th>
 				<th>Place</th>
 				<th>Profile Picture</th>
 				<th>Show</th>
 				<th>Edit</th>
 				<th>Delete</th>
 			</thead>
 			<tbody>
 				@if($adds)
 				@foreach($adds as $add)
 				<tr>
 				<td>{{ $add->id }}</td>
 				<td>{{ $add->first_name }}</td>
 				<td>{{ $add->last_name }}</td>
 				<td>{{ $add->email }}</td>
 				<td>{{ $add->job_title }}</td>
 				<td>{{ $add->phone }}</td>
 				<td>{{ $add->place }}</td>
 				<td><img src="myfiles/{{ $add->image }}" style="border-radius: 50%" width="80px"></td>
 				<td> <a class="btn btn-info" href="{{ route('blog.show',$add->id) }}">Show</a></td>
 				<td> <a class="btn btn-primary" href="{{ route('blog.edit',$add->id) }}">Edit</a></td>
 				<td>
 					<form method="post" action="{{ route('blog.destroy',$add->id)}}">
 						@csrf
 						@method('DELETE')
 						<button class="btn btn-danger" type="sumbit">Delete</button>
 					</form>
 				</td>
 				
 			</tr>
 				@endforeach
 				@endif
 			</tbody>
 			
 		</table>
 			
 			
 		</div>
 		
 	</div>
 	
 </div>
</div>
 @endsection

resources/views/layouts/view.blade.php
@extends('layouts.app')
@extends('layouts.header')

@section('content')

    <div class="row">
       
        <div class="col-lg-1">
            <a class="btn btn-primary" href="{{ url('blog') }}"> Back</a>
        </div>
    </div>
<div class="container">
    <table class="table table-bordered">
        <tr>
            <th>First_Name:</th>
            <td>{{ $add->first_name }}</td>
        </tr>
        <tr>
            <th>Last_Name:</th>
            <td>{{ $add->last_name }}</td>
        </tr>
        <tr>
            <th>Email:</th>
            <td>{{ $add->email }}</td>
        </tr>
        <tr>
            <th>Job_title:</th>
            <td>{{ $add->job_title }}</td>
        </tr>
        <tr>
            <th>Phone:</th>
            <td>{{ $add->phone }}</td>
        </tr>
        <tr>
            <th>Place:</th>
            <td>{{ $add->place }}</td>
        </tr>
        <tr>
            <th>Profile Picture:</th>
            <td><img src="myfiles/{{ $add->image }}" style="border-radius: 50%" width="80px"></td>       
        </tr>

    </table>
</div>
@endsection